models:
  logistic_regression:
    enabled: true
    parameters:
      penalty: "l2"
      solver: "liblinear"
      max_iter: 100

  decision_tree:
    enabled: true
    parameters:
      criterion: "gini"
      max_depth: 10

  random_forest:
    enabled: true
    parameters:
      n_estimators: 100
      max_depth: 15

  xgboost:
    enabled: true
    parameters:
      learning_rate: 0.05 #0.01
      n_estimators: 500 #5000
      eval_metric: logloss
      max_depth: 5
      early_stopping_rounds: 5
      objective: 'binary:logistic'

  neural_network:
    enabled: true
    parameters:
      hidden_layers: [64, 32]
      activation: "relu"
      dropout_rate: 0.2
      epochs: 10
      batch_size: 32
      learning_rate: 0.001

training:
  test_size: 0.3
  random_state: 42

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score"]


